services:
  postgres:
    image: postgres:14.5
    ports:
      - 54325:5432
    environment:
      - POSTGRES_PASSWORD=fddomain
      - POSTGRES_USER=fddomain
      - POSTGRES_DB=fddomain

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    container_name: metabase
    depends_on:
      - postgres
